import { RealtimeChannel } from '@supabase/supabase-js';
import { Expense, ExpenseType } from '../types';
import { supabase } from './supabase';

// Construction expense ledger: public read, admin-only writes (same is_admin() RLS rule as donations).
// Receipt photos live in the public "receipts" storage bucket; rows store their storage paths.

export const EXPENSE_TYPES: ExpenseType[] = ['Material', 'Labour', 'Machinery', 'Transport', 'Other'];
const RECEIPTS_BUCKET = 'receipts';

interface ExpenseRow {
  id: number;
  date: string;
  type: string;
  description: string;
  quantity: number | null;
  unit: string | null;
  rate: number | null;
  amount: number;
  payee: string | null;
  payment_method: string | null;
  notes: string | null;
  receipts: string[];
  created_at: number;
  updated_at: number | null;
}

const toExpenseRow = (e: Expense): ExpenseRow => ({
  id: Number(e.id),
  date: e.date,
  type: e.type,
  description: e.description,
  quantity: e.quantity ?? null,
  unit: e.unit || null,
  rate: e.rate ?? null,
  amount: e.amount,
  payee: e.payee || null,
  payment_method: e.paymentMethod || null,
  notes: e.notes || null,
  receipts: e.receipts,
  created_at: e.createdAt || Date.now(),
  updated_at: e.updatedAt ?? null,
});

const fromExpenseRow = (row: any): Expense => ({
  id: String(row.id),
  date: row.date,
  type: (EXPENSE_TYPES as string[]).includes(row.type) ? row.type : 'Other',
  description: row.description || '',
  quantity: row.quantity ?? undefined,
  unit: row.unit || undefined,
  rate: row.rate ?? undefined,
  amount: Number(row.amount) || 0,
  payee: row.payee || undefined,
  paymentMethod: row.payment_method || undefined,
  notes: row.notes || undefined,
  receipts: Array.isArray(row.receipts) ? row.receipts : [],
  createdAt: typeof row.created_at === 'number' ? row.created_at : Date.now(),
  updatedAt: row.updated_at ?? undefined,
});

export const fetchExpenses = async (): Promise<Expense[]> => {
  const { data, error } = await supabase.from('expenses').select('*').order('date', { ascending: false });
  if (error) throw new Error(error.message);
  return (data || []).map(fromExpenseRow);
};

/** Insert a new expense; the database assigns its sequential id */
export const insertExpense = async (expense: Omit<Expense, 'id'>): Promise<Expense> => {
  const { id: _assignedByDb, ...row } = toExpenseRow({ ...expense, id: '0' });
  const { data, error } = await supabase.from('expenses').insert(row).select().single();
  if (error) throw new Error(error.message);
  return fromExpenseRow(data);
};

export const updateExpense = async (expense: Expense): Promise<Expense> => {
  const { data, error } = await supabase
    .from('expenses')
    .update(toExpenseRow({ ...expense, updatedAt: Date.now() }))
    .eq('id', Number(expense.id))
    .select()
    .single();
  if (error) throw new Error(error.message);
  return fromExpenseRow(data);
};

export const deleteExpense = async (expense: Expense): Promise<void> => {
  const { error } = await supabase.from('expenses').delete().eq('id', Number(expense.id));
  if (error) throw new Error(error.message);
  // Best effort: the row is gone either way, so don't fail the delete over orphaned photos
  if (expense.receipts.length) await supabase.storage.from(RECEIPTS_BUCKET).remove(expense.receipts).catch(() => {});
};

export const subscribeToExpenseChanges = (
  onUpsert: (expense: Expense) => void,
  onDelete: (id: string) => void
): RealtimeChannel =>
  supabase
    .channel('expenses-realtime')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'expenses' }, (payload) => {
      if (payload.eventType === 'DELETE') onDelete(String((payload.old as any).id));
      else onUpsert(fromExpenseRow(payload.new));
    })
    .subscribe();

// ---- Receipt photos ----

/** Upload an (already compressed) receipt image; returns its storage path */
export const uploadReceipt = async (blob: Blob, date: string): Promise<string> => {
  const path = `${date || 'undated'}/${crypto.randomUUID()}.jpg`;
  const { error } = await supabase.storage.from(RECEIPTS_BUCKET).upload(path, blob, {
    contentType: 'image/jpeg',
    cacheControl: '31536000', // paths are unique, so the file never changes
  });
  if (error) throw new Error(error.message);
  return path;
};

export const removeReceipts = async (paths: string[]) => {
  if (paths.length) await supabase.storage.from(RECEIPTS_BUCKET).remove(paths);
};

export const receiptUrl = (path: string) => supabase.storage.from(RECEIPTS_BUCKET).getPublicUrl(path).data.publicUrl;

/**
 * Run once in the Supabase SQL editor. Requires public.is_admin() (see SUPABASE_SQL_SETUP in supabase.ts).
 */
export const EXPENSES_SQL_SETUP = `create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date text not null,
  type text not null,
  description text not null,
  quantity numeric,
  unit text,
  rate numeric,
  amount bigint not null check (amount > 0),
  payee text,
  payment_method text,
  notes text,
  receipts jsonb not null default '[]'::jsonb,
  created_at bigint not null default (extract(epoch from now()) * 1000)::bigint,
  updated_at bigint
);
alter table public.expenses enable row level security;
create policy "Public read expenses" on public.expenses for select using (true);
create policy "Admins insert expenses" on public.expenses for insert to authenticated with check (public.is_admin());
create policy "Admins update expenses" on public.expenses for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "Admins delete expenses" on public.expenses for delete to authenticated using (public.is_admin());
alter publication supabase_realtime add table public.expenses;

-- Receipt photos: public bucket (anyone can view by URL), only admins can upload/replace/delete
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('receipts', 'receipts', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;
create policy "Admins upload receipts" on storage.objects for insert to authenticated with check (bucket_id = 'receipts' and public.is_admin());
create policy "Admins update receipts" on storage.objects for update to authenticated using (bucket_id = 'receipts' and public.is_admin());
create policy "Admins delete receipts" on storage.objects for delete to authenticated using (bucket_id = 'receipts' and public.is_admin());

notify pgrst, 'reload schema';`;
