// Registers the Workbox service worker (generated by vite-plugin-pwa) and makes updates show up promptly.
// The SW uses skipWaiting + clientsClaim, so after a deploy the new worker takes over the open page;
// we then reload once so the page actually runs the new code instead of the previously cached build.

const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000;

export const registerServiceWorker = (options: { canReload?: () => boolean } = {}) => {
  if (!import.meta.env.PROD || !('serviceWorker' in navigator)) return;
  const canReload = options.canReload ?? (() => true);

  // No controller yet means this is the very first install, not an update: nothing to reload
  const hadController = !!navigator.serviceWorker.controller;
  let pendingReload = false;
  let reloading = false;

  const reloadIfAllowed = () => {
    if (reloading) return;
    if (canReload()) {
      reloading = true;
      window.location.reload();
    } else {
      pendingReload = true; // e.g. admin is mid-form; reload on the next navigation instead
    }
  };

  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (hadController) reloadIfAllowed();
  });

  // Retry a deferred reload once the page says it's safe (called on in-app navigation)
  window.addEventListener('popstate', () => pendingReload && reloadIfAllowed());
  window.addEventListener('admin:navigate', () => pendingReload && reloadIfAllowed());

  window.addEventListener('load', async () => {
    try {
      const registration = await navigator.serviceWorker.register('/sw.js', { scope: '/' });
      // Installed apps can stay open for days without a navigation, so check for new deploys
      // when the app returns to the foreground and periodically while it's open.
      const checkForUpdate = () => registration.update().catch(() => {});
      document.addEventListener('visibilitychange', () => {
        if (document.visibilityState === 'visible') checkForUpdate();
      });
      setInterval(checkForUpdate, UPDATE_CHECK_INTERVAL_MS);
    } catch (err) {
      console.warn('Service worker registration failed', err);
    }
  });
};
